# (C) Copyright 2023 Syncsort Incorporated. All rights reserved.

{{- include "sch.config.init" (list . "documentSvc.sch.chart.config.values") }}

kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "sch.names.fullCompName" (list . .sch.chart.components.defaultNetworkPolicy.name) | quote }}
  labels:
{{ include "sch.metadata.labels.standard" (list . .sch.chart.components.defaultNetworkPolicy.name) | indent 4 }}
spec:
  podSelector:
    matchLabels:
      release: {{ .Release.Name }}
  ingress:
  - from: []
  policyTypes:
  - Ingress